# dev
spring:
  config:
    activate:
      on-profile: dev

  # datasource
  maria-datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://${rds_host}:3306/freedom_day
    username: ${rds_username}
    password: ${rds_password}
    maximum-pool-size: 10
    connection-timeout: 5000 # (ms)

 # redis
  data:
    redis:
      host: freedom-day-refreshtoken-redis-ro.v9dkc7.ng.0001.apn2.cache.amazonaws.com
      port: 6379
      password:

  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${google_smtp_account}
    password: ${google_smtp_pw}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    templates:
      path: templates/

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate # *******
    properties:
      hibernate:

security:
  jwt-key: ${security_jwt_key}
