# dev
spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      host: freedom-day-refreshtoken-redis-ro.v9dkc7.ng.0001.apn2.cache.amazonaws.com
      port: 6379
      password:


  datasource:
    url: jdbc:mariadb://${rds_host}:3306/freedom_day # TODO)
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${rds_username}
    password: ${rds_password}

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate # *******
    properties:
      hibernate:

security:
  jwt-key: ${security_jwt_key}
