= API 명세
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toc-title: 목차
:toclevels: 2
:sectlinks:
:sectnums:
:docinfo: shared-head


== 멤버
=== 로그인
operation::member-controller-test/sign-in[snippets='http-request,http-response,request-fields,response-fields-response']
==== Error Code
[cols="1,3", options="header"]
|===
| Code | Description
| ACCOUNT-001 | 존재하지 않은 유저
| ACCOUNT-002 | 비밀번호 일치 실패
|===


=== 회원가입
operation::member-controller-test/sign-up[snippets='http-request,http-response,request-fields']
==== Error Code
[cols="1,3", options="header"]
|===
| Code | Description
| ACCOUNT-005 | 이미 사용하고 있는 이메일
| ACCOUNT-006 | 인증되지 않은 이메일
|===

=== 로그아웃
operation::member-controller-test/sign-out[snippets='http-request,http-response']
==== Error Code
[cols="1,3", options="header"]
|===
| Code | Description
| ACCOUNT-005 | 이미 사용하고 있는 이메일
|===

=== 이메일 인증 발송
operation::member-controller-test/send-mail[snippets='http-request,http-response,request-fields']
==== Error Code
[cols="1,3", options="header"]
|===
| Code | Description
| ACCOUNT-005 | 이미 사용하고 있는 이메일
|===


== 대출
=== 내 대출 정보
operation::loan-controller-test/user-loan-info[snippets='http-request,http-response,response-fields-response']
==== Error Code
[cols="1,3", options="header"]
|===
| Code | Description
| ACCOUNT-001 | 존재하지 않은 유저
|===

=== 대출 통계
operation::loan-controller-test/loan-statistics[snippets='http-request,http-response,response-fields-response']
==== Error Code
[cols="1,3", options="header"]
|===
| Code | Description
|===

=== 대출 생성
operation::loan-controller-test/create[snippets='http-request,http-response,request-fields']
==== Error Code
[cols="1,3", options="header"]
|===
| Code | Description
|===

=== 대출 상세
operation::loan-controller-test/detail[snippets='http-request,http-response,request-fields,response-fields-response']
==== Error Code
[cols="1,3", options="header"]
|===
| Code | Description
|===

=== 대출 내역 추가
operation::loan-controller-test/add-repayment-details[snippets='http-request,http-response,request-fields']
==== Error Code
[cols="1,3", options="header"]
|===
| Code | Description
| LOAN-001 | 존재하지 않은 대출
| LOAN-002 | 상환 내역이 이미 존재함
| LOAN-003 | 대출을 추가할 권한이 없음 ex) 주인아님
|===
